// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Expensely.Persistence.Reporting.Migrations
{
    public partial class AddAuditingColumnsToTransactionSummary : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary");

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedOnUtc",
                table: "TransactionSummary",
                type: "datetime2",
                nullable: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "ModifiedOnUtc",
                table: "TransactionSummary",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary",
                column: "UserId",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary");

            migrationBuilder.DropColumn(
                name: "CreatedOnUtc",
                table: "TransactionSummary");

            migrationBuilder.DropColumn(
                name: "ModifiedOnUtc",
                table: "TransactionSummary");

            migrationBuilder.AddForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary",
                column: "UserId",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
