// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Expensely.Persistence.Reporting.Migrations
{
    public partial class ChangeIndexOnTransactionSummary : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TransactionSummary",
                table: "TransactionSummary");

            migrationBuilder.DropIndex(
                name: "IX_TransactionSummary_UserId",
                table: "TransactionSummary");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TransactionSummary",
                table: "TransactionSummary",
                column: "Id")
                .Annotation("SqlServer:Clustered", false);

            migrationBuilder.CreateIndex(
                name: "IX_TransactionSummary_UserId",
                table: "TransactionSummary",
                column: "UserId")
                .Annotation("SqlServer:Clustered", true);

            migrationBuilder.AddForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary",
                column: "UserId",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
            
            migrationBuilder.Sql("DROP INDEX [IX_TransactionSummary_UserId_Year_Month_TransactionType_Currency] ON [TransactionSummary]");

            migrationBuilder.Sql(
              @"CREATE INDEX [IX_TransactionSummary_UserId_Year_Month_Currency_TransactionType] ON
                [TransactionSummary] ([UserId], [Year], [Month], [Currency], [TransactionType])
                INCLUDE ([Amount])");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP INDEX [IX_TransactionSummary_UserId_Year_Month_Currency_TransactionType] ON [TransactionSummary]");

            migrationBuilder.Sql(
              @"CREATE INDEX [IX_TransactionSummary_UserId_Year_Month_TransactionType_Currency] ON
                [TransactionSummary] ([UserId], [Year], [Month], [TransactionType], [Currency])");

            migrationBuilder.DropForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TransactionSummary",
                table: "TransactionSummary");

            migrationBuilder.DropIndex(
                name: "IX_TransactionSummary_UserId",
                table: "TransactionSummary");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TransactionSummary",
                table: "TransactionSummary",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_TransactionSummary_UserId",
                table: "TransactionSummary",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary",
                column: "UserId",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
