// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Expensely.Persistence.Reporting.Migrations
{
    public partial class AddCategoryTransactionSummary : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary");

            migrationBuilder.CreateTable(
                name: "CategoryTransactionSummary",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Year = table.Column<int>(type: "int", nullable: false),
                    Month = table.Column<int>(type: "int", nullable: false),
                    Category = table.Column<int>(type: "int", nullable: false),
                    Amount = table.Column<decimal>(type: "decimal(12,4)", precision: 12, scale: 4, nullable: false),
                    Currency = table.Column<int>(type: "int", nullable: false),
                    TransactionType = table.Column<int>(type: "int", nullable: false),
                    CreatedOnUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedOnUtc = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CategoryTransactionSummary", x => x.Id)
                        .Annotation("SqlServer:Clustered", false);
                    table.ForeignKey(
                        name: "FK_CategoryTransactionSummary_User_UserId",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CategoryTransactionSummary_UserId",
                table: "CategoryTransactionSummary",
                column: "UserId")
                .Annotation("SqlServer:Clustered", true);

            migrationBuilder.Sql(
              @"CREATE INDEX [IX_CategoryTransactionSummary_UserId_Year_Month_TransactionType_Currency_Category] ON
                [CategoryTransactionSummary] ([UserId], [Year], [Month], [TransactionType], [Currency], [Category])
                INCLUDE ([Amount])");

            migrationBuilder.AddForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary",
                column: "UserId",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary");

            migrationBuilder.DropTable(
                name: "CategoryTransactionSummary");

            migrationBuilder.AddForeignKey(
                name: "FK_TransactionSummary_User_UserId",
                table: "TransactionSummary",
                column: "UserId",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
