// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Expensely.Persistence.Application.Migrations
{
    public partial class AddDefaultValueToMessageProcessed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder) =>
            migrationBuilder.AlterColumn<bool>(
                name: "Processed",
                table: "Message",
                type: "bit",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "bit");

        protected override void Down(MigrationBuilder migrationBuilder) =>
            migrationBuilder.AlterColumn<bool>(
                name: "Processed",
                table: "Message",
                type: "bit",
                nullable: false,
                oldClrType: typeof(bool),
                oldType: "bit",
                oldDefaultValue: false);
    }
}
