name: Publish code coverage

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "5.0.202"

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ./Expensely.sln

      - name: Build
        run: dotnet build ./Expensely.sln --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test ./test/Expensely.Domain.UnitTests --configuration Release --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=../../TestResults/ /p:CoverletOutputFormat=json
          dotnet test ./test/Expensely.Application.UnitTests --configuration Release --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=../../TestResults/ /p:CoverletOutputFormat=cobertura /p:MergeWith=../../TestResults/coverage.json

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./server/TestResults/coverage.cobertura.xml
