name: Server - Build

on:
  push:
    paths:
      - "server/**"

env:
  DOTNET_VERSION: "5.0.102"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ./server/Expensely.sln

      - name: Build
        run: dotnet build ./server/Expensely.sln --configuration Release --no-restore
