name: Test

on:
 push

env:
  DOTNET_VERSION: "6.0.100"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ./Expensely.sln

      - name: Build
        run: dotnet build ./Expensely.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Expensely.sln --configuration Release --no-restore --verbosity normal
